name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ${DOCKER_REGISTRY}/${IMAGE}:latest .
      env:
        DOCKER_REGISTRY: docker.io
        IMAGE: sireto/custom-domain
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${DOCKER_REGISTRY}
      env:
        DOCKER_REGISTRY: docker.io
    - name: Push the Docker image
      run: docker push ${DOCKER_REGISTRY}/${IMAGE}:latest
      env:
        DOCKER_REGISTRY: docker.io
        IMAGE: sireto/custom-domain
